name: ci
on:
  push:
  pull_request:
  schedule:
  - cron:  '0 3 * * 6' # 3am Saturday
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['9.6', '9.4', '9.2', '9.0', '8.10', '8.8']
        include:
        - os: windows-latest
        - os: macOS-latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - run: |
        cabal v2-configure --enable-tests --disable-documentation --write-ghc-environment-files=always
        cabal v2-build --dry-run
        # The dry run generates dist-newstyle/cache/plan.json
    - uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-plan-${{ hashFiles('dist-newstyle/cache/plan.json') }}
        restore-keys: ${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-
    - uses: ndmitchell/neil@master
      with:
        hlint-arguments: src
        install-fsatrace: true
